name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  code-analysis:
    name: "Static code analysis"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Run code analyzer
        run: mvn checkstyle:check

  test:
    name: "Run automated tests"
    needs: code-analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Run tests
        run: mvn test

  jar-build:
    name: "Build jar"
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Build jar
        run: mvn package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v5
        with:
          name: lab6-jar
          path: target/*.jar

  publish-artifacts:
    name: "Publish to GitHub Packages"
    needs: jar-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'
          server-id: github 
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
